import type { Locale, LocalizedText } from "@/lib/learning-api";

export const studentCopy = {
  en: {
    appName: "Student workspace",
    loading: "Loading your learning workspace…",
    offline: "You are offline. Reconnect to refresh or save learning activity.",
    stale: "Showing the last loaded lesson. Online actions are paused while you are offline.",
    unavailable: "The learning service is unavailable right now.",
    permission: "Your session cannot access this student workspace.",
    retry: "Retry",
    navigation: "Student workspace navigation",
    languageSelector: "Interface language",
    home: "Home",
    study: "Study",
    practice: "Practice",
    progress: "Progress",
    academicTrack: "Academic track",
    homeTitle: "Your learning desk",
    homeSubtitle: "Pick up the lesson, continue a saved practice attempt, or review progress from one desktop workspace.",
    synthetic: "Synthetic fixture · no real curriculum",
    currentLesson: "Current lesson",
    continueStudy: "Continue studying",
    academicContext: "Academic context",
    active: "Active",
    onboarding: "Onboarding required",
    yearLevel: "Year level",
    track: "Academic track",
    trackConfigured: "Configured by the learning service",
    contextLocked: "Your active academic context is protected. Changing it requires the explicit full-reset flow below.",
    academicTrackTitle: "Academic track & curriculum",
    academicTrackSubtitle: "View the track assigned to your account, choose another available track, and review exactly what changes before confirming.",
    manageAcademicTrack: "Manage academic track",
    manageAcademicTrackHelp: "Open the dedicated track page to view available tracks or request a full reset.",
    currentAcademicTrack: "Current academic context",
    openAcademicTrack: "Open academic track settings",
    trackChangeSafetyTitle: "Changing track affects your learning context",
    trackChangeSafetyBody: "Your previous track, attempts and progress remain archived for history. Mastery and answers are not moved into the new track.",
    resetReview: "Review track-change consequences",
    resetTitle: "Changing track is a full reset",
    resetBody: "Your previous academic context, attempts, and mastery are archived instead of deleted. In-progress work can be left unfinished as part of that transition.",
    resetGap: "Available tracks come only from the approved catalogue for your account. You never need to enter a track code or ID.",
    studyTitle: "Study workspace",
    studySubtitle: "Read the published lesson with a comfortable desktop measure and language-aware content direction.",
    contentVersion: "Content version",
    lessonEmpty: "No published lesson is available in this context.",
    practiceTitle: "Practice workspace",
    practiceSubtitle: "Question selection and order are preserved by the learning service for your attempt. This screen does not choose or reshuffle them.",
    authoritative: "Saved assessment attempt",
    authoritativeNote: "Starting creates a saved attempt; reconnecting resumes that same question order.",
    start: "Start new practice",
    starting: "Starting practice…",
    resume: "Resume practice",
    submitting: "Saving and submitting…",
    submit: "Save answers and submit",
    answerRequired: "Answer every question before submitting.",
    conflict: "The attempt changed while you were working. The latest saved attempt has been reloaded; review your answers and continue.",
    noAttempt: "No practice is in progress.",
    question: "Question",
    textAnswer: "Answer",
    answered: "answered",
    result: "Practice result",
    attemptStatus: "Attempt status",
    statusInProgress: "In progress",
    statusSubmitted: "Submitted",
    statusGraded: "Graded",
    statusAbandoned: "Abandoned",
    progressTitle: "Progress workspace",
    progressSubtitle: "Progress is read from your active academic context and its saved learning record.",
    mastery: "Mastery",
    emptyProgress: "Complete a practice to create your first progress snapshot.",
    snapshots: "Progress snapshots",
    openStudy: "Open study workspace",
    openPractice: "Open practice workspace",
    openProgress: "Open progress workspace",
    lessonStatus: "Lesson ready",
    attemptReady: "Practice ready",
    offlineStatus: "Offline mode",
    serviceStatus: "Learning service",
    skip: "Skip to main content",
  },
  ar: {
    appName: "مساحة الطالب",
    loading: "جارٍ تحميل مساحة التعلّم…",
    offline: "أنت غير متصل. أعد الاتصال لتحديث أو حفظ نشاط التعلّم.",
    stale: "نعرض آخر درس تم تحميله. الإجراءات التي تحتاج اتصالًا متوقفة مؤقتًا.",
    unavailable: "خدمة التعلّم غير متاحة حاليًا.",
    permission: "لا تسمح جلستك بالوصول إلى مساحة الطالب هذه.",
    retry: "إعادة المحاولة",
    navigation: "التنقل في مساحة الطالب",
    languageSelector: "لغة الواجهة",
    home: "الرئيسية",
    study: "المذاكرة",
    practice: "التدريب",
    progress: "التقدّم",
    academicTrack: "المسار الأكاديمي",
    homeTitle: "مكتبك الدراسي",
    homeSubtitle: "تابع الدرس أو أكمل محاولة تدريب محفوظة أو راجع تقدّمك من مساحة واحدة.",
    synthetic: "محتوى اصطناعي تجريبي · ليس منهجًا حقيقيًا",
    currentLesson: "الدرس الحالي",
    continueStudy: "تابع المذاكرة",
    academicContext: "السياق الأكاديمي",
    active: "نشط",
    onboarding: "يلزم إعداد السياق",
    yearLevel: "السنة الدراسية",
    track: "المسار الأكاديمي",
    trackConfigured: "مُحدد بواسطة خدمة التعلّم",
    contextLocked: "سياقك الأكاديمي النشط محمي. تغييره يتطلب مسار إعادة الضبط الكامل والصريح أدناه.",
    academicTrackTitle: "المسار الأكاديمي والمنهج",
    academicTrackSubtitle: "راجع المسار المخصص لحسابك، واختر مسارًا آخر متاحًا، واعرف بالضبط ما الذي سيتغير قبل التأكيد.",
    manageAcademicTrack: "إدارة المسار الأكاديمي",
    manageAcademicTrackHelp: "افتح صفحة المسار المخصصة لعرض المسارات المتاحة أو طلب إعادة ضبط كاملة.",
    currentAcademicTrack: "السياق الأكاديمي الحالي",
    openAcademicTrack: "فتح إعدادات المسار الأكاديمي",
    trackChangeSafetyTitle: "تغيير المسار يؤثر على سياق التعلّم",
    trackChangeSafetyBody: "يبقى مسارك السابق ومحاولاتك وتقدّمك مؤرشفين للتاريخ. لا يتم نقل الإتقان أو الإجابات إلى المسار الجديد.",
    resetReview: "راجع نتائج تغيير المسار",
    resetTitle: "تغيير المسار يتطلب إعادة ضبط كاملة",
    resetBody: "تتم أرشفة سياقك السابق ومحاولاتك وإتقانك بدل حذف السجل. وقد يبقى أي عمل جارٍ غير مكتمل أثناء الانتقال.",
    resetGap: "المسارات المتاحة تأتي فقط من القائمة المعتمدة لحسابك. لن تحتاج إلى كتابة كود أو معرّف مسار.",
    studyTitle: "مساحة المذاكرة",
    studySubtitle: "اقرأ الدرس المنشور بعرض مريح واتجاه محتوى مناسب للغة.",
    contentVersion: "إصدار المحتوى",
    lessonEmpty: "لا يوجد درس منشور متاح في هذا السياق.",
    practiceTitle: "مساحة التدريب",
    practiceSubtitle: "يتم حفظ اختيار الأسئلة وترتيبها لمحاولتك. هذه الشاشة لا تختارها ولا تعيد ترتيبها.",
    authoritative: "محاولة تقييم محفوظة",
    authoritativeNote: "بدء التدريب ينشئ محاولة محفوظة، وإعادة الاتصال تستأنف نفس ترتيب الأسئلة.",
    start: "ابدأ تدريبًا جديدًا",
    starting: "جارٍ بدء التدريب…",
    resume: "استئناف التدريب",
    submitting: "جارٍ الحفظ والإرسال…",
    submit: "احفظ الإجابات وأرسل",
    answerRequired: "أجب عن جميع الأسئلة قبل الإرسال.",
    conflict: "تغيّرت المحاولة أثناء العمل. تم تحميل أحدث نسخة محفوظة؛ راجع إجاباتك ثم تابع.",
    noAttempt: "لا توجد محاولة تدريب جارية.",
    question: "السؤال",
    textAnswer: "الإجابة",
    answered: "تمت الإجابة",
    result: "نتيجة التدريب",
    attemptStatus: "حالة المحاولة",
    statusInProgress: "قيد التنفيذ",
    statusSubmitted: "تم الإرسال",
    statusGraded: "تم التصحيح",
    statusAbandoned: "منتهية دون إكمال",
    progressTitle: "مساحة التقدّم",
    progressSubtitle: "يُقرأ التقدّم من سياقك الأكاديمي النشط وسجل التعلّم المحفوظ.",
    mastery: "الإتقان",
    emptyProgress: "أكمل تدريبًا لإنشاء أول سجل للتقدّم.",
    snapshots: "سجلات التقدّم",
    openStudy: "افتح مساحة المذاكرة",
    openPractice: "افتح مساحة التدريب",
    openProgress: "افتح مساحة التقدّم",
    lessonStatus: "الدرس جاهز",
    attemptReady: "التدريب جاهز",
    offlineStatus: "وضع عدم الاتصال",
    serviceStatus: "خدمة التعلّم",
    skip: "انتقل إلى المحتوى الرئيسي",
  },
  fr: {
    appName: "Espace élève",
    loading: "Chargement de votre espace d’apprentissage…",
    offline: "Vous êtes hors ligne. Reconnectez-vous pour actualiser ou enregistrer l’activité.",
    stale: "La dernière leçon chargée reste visible. Les actions nécessitant une connexion sont suspendues.",
    unavailable: "Le service d’apprentissage est indisponible pour le moment.",
    permission: "Votre session ne peut pas accéder à cet espace élève.",
    retry: "Réessayer",
    navigation: "Navigation de l’espace élève",
    languageSelector: "Langue de l’interface",
    home: "Accueil",
    study: "Étude",
    practice: "Exercice",
    progress: "Progression",
    academicTrack: "Parcours académique",
    homeTitle: "Votre bureau d’apprentissage",
    homeSubtitle: "Reprenez la leçon, continuez une tentative enregistrée ou consultez votre progression depuis un seul espace.",
    synthetic: "Contenu synthétique de test · aucun programme réel",
    currentLesson: "Leçon actuelle",
    continueStudy: "Continuer l’étude",
    academicContext: "Contexte académique",
    active: "Actif",
    onboarding: "Configuration requise",
    yearLevel: "Niveau scolaire",
    track: "Parcours académique",
    trackConfigured: "Configuré par le service d’apprentissage",
    contextLocked: "Votre contexte académique actif est protégé. Le changer exige le flux explicite de réinitialisation complète ci-dessous.",
    academicTrackTitle: "Parcours académique et programme",
    academicTrackSubtitle: "Consultez le parcours attribué à votre compte, choisissez un autre parcours disponible et voyez exactement ce qui changera avant confirmation.",
    manageAcademicTrack: "Gérer le parcours académique",
    manageAcademicTrackHelp: "Ouvrez la page dédiée pour voir les parcours disponibles ou demander une réinitialisation complète.",
    currentAcademicTrack: "Contexte académique actuel",
    openAcademicTrack: "Ouvrir les paramètres du parcours",
    trackChangeSafetyTitle: "Changer de parcours affecte votre contexte d’apprentissage",
    trackChangeSafetyBody: "Votre ancien parcours, vos tentatives et votre progression restent archivés. La maîtrise et les réponses ne sont pas transférées vers le nouveau parcours.",
    resetReview: "Voir les conséquences d’un changement de parcours",
    resetTitle: "Changer de parcours déclenche une réinitialisation complète",
    resetBody: "Votre ancien contexte, vos tentatives et votre maîtrise sont archivés au lieu d’être supprimés. Un travail en cours peut rester inachevé pendant la transition.",
    resetGap: "Les parcours disponibles proviennent uniquement de la liste approuvée pour votre compte. Vous n’avez jamais à saisir de code ou d’identifiant de parcours.",
    studyTitle: "Espace d’étude",
    studySubtitle: "Lisez la leçon publiée dans une largeur confortable, avec une direction adaptée à la langue du contenu.",
    contentVersion: "Version du contenu",
    lessonEmpty: "Aucune leçon publiée n’est disponible dans ce contexte.",
    practiceTitle: "Espace d’exercice",
    practiceSubtitle: "La sélection et l’ordre des questions sont conservés pour votre tentative. Cet écran ne les choisit ni ne les remélange.",
    authoritative: "Tentative d’évaluation enregistrée",
    authoritativeNote: "Le démarrage crée une tentative enregistrée ; la reconnexion reprend exactement le même ordre des questions.",
    start: "Commencer un nouvel exercice",
    starting: "Démarrage de l’exercice…",
    resume: "Reprendre l’exercice",
    submitting: "Enregistrement et envoi…",
    submit: "Enregistrer les réponses et envoyer",
    answerRequired: "Répondez à toutes les questions avant l’envoi.",
    conflict: "La tentative a changé pendant votre travail. La dernière version enregistrée a été rechargée ; vérifiez vos réponses puis continuez.",
    noAttempt: "Aucun exercice n’est en cours.",
    question: "Question",
    textAnswer: "Réponse",
    answered: "répondues",
    result: "Résultat de l’exercice",
    attemptStatus: "Statut de la tentative",
    statusInProgress: "En cours",
    statusSubmitted: "Envoyée",
    statusGraded: "Corrigée",
    statusAbandoned: "Abandonnée",
    progressTitle: "Espace de progression",
    progressSubtitle: "La progression provient de votre contexte académique actif et de votre historique d’apprentissage enregistré.",
    mastery: "Maîtrise",
    emptyProgress: "Terminez un exercice pour créer votre premier instantané de progression.",
    snapshots: "Instantanés de progression",
    openStudy: "Ouvrir l’espace d’étude",
    openPractice: "Ouvrir l’espace d’exercice",
    openProgress: "Ouvrir la progression",
    lessonStatus: "Leçon prête",
    attemptReady: "Exercice prêt",
    offlineStatus: "Mode hors ligne",
    serviceStatus: "Service d’apprentissage",
    skip: "Aller au contenu principal",
  },
} as const;

export function directionForLocale(locale: Locale): "rtl" | "ltr" {
  return locale === "ar" ? "rtl" : "ltr";
}

export function localize(value: LocalizedText, locale: Locale): string {
  return value[locale] ?? value.en ?? value.ar ?? value.fr ?? "";
}
