import type { Locale, LocalizedText } from "@/lib/learning-api";

export const studentCopy = {
  en: {
    appName: "Student workspace",
    loading: "Loading your learning workspace…",
    offline: "You are offline. Reconnect to refresh or save learning activity.",
    stale: "Showing the last loaded lesson. Server actions are paused while you are offline.",
    unavailable: "The learning service is unavailable right now.",
    permission: "Your session cannot access this student workspace.",
    retry: "Retry",
    navigation: "Student workspace navigation",
    home: "Home",
    study: "Study",
    practice: "Practice",
    progress: "Progress",
    homeTitle: "Your learning desk",
    homeSubtitle: "Pick up the lesson, continue a server-owned practice attempt, or review progress from one desktop workspace.",
    synthetic: "Synthetic fixture · no real curriculum",
    currentLesson: "Current lesson",
    continueStudy: "Continue studying",
    academicContext: "Academic context",
    active: "Active",
    onboarding: "Onboarding required",
    yearLevel: "Year level",
    track: "Academic track",
    trackConfigured: "Configured by the learning service",
    contextLocked: "The active academic context is backend-owned and locked after onboarding.",
    resetReview: "Review track-change consequences",
    resetTitle: "Changing track is a full reset",
    resetBody: "The Backend archives the prior academic context, attempts, and mastery instead of deleting history. In-progress work can be abandoned as part of that transition.",
    resetGap: "This Web client does not invent a track catalogue. A selectable board/syllabus/track contract is still required before a professional change-track control can be enabled.",
    studyTitle: "Study workspace",
    studySubtitle: "Read the published lesson with a comfortable desktop measure and language-aware content direction.",
    contentVersion: "Content version",
    lessonEmpty: "No published lesson is available in this context.",
    practiceTitle: "Practice workspace",
    practiceSubtitle: "Question selection and order come only from the persisted Backend attempt. The Web client never generates an assessment seed or authoritative order.",
    authoritative: "Server-authoritative attempt",
    authoritativeNote: "Starting creates a Backend attempt; reconnecting resumes that same persisted order.",
    start: "Start new practice",
    starting: "Starting practice…",
    resume: "Resume practice",
    submitting: "Saving and submitting…",
    submit: "Save answers and submit",
    answerRequired: "Answer every question before submitting.",
    conflict: "The attempt changed on the server. The authoritative persisted attempt has been reloaded; review your answers and continue.",
    noAttempt: "No practice is in progress.",
    question: "Question",
    textAnswer: "Answer",
    saved: "Saved",
    result: "Practice result",
    attemptStatus: "Attempt status",
    progressTitle: "Progress workspace",
    progressSubtitle: "Progress is read from the active academic context; this client does not calculate mastery independently.",
    mastery: "Mastery",
    emptyProgress: "Complete a practice to create your first progress snapshot.",
    snapshots: "Progress snapshots",
    openStudy: "Open study workspace",
    openPractice: "Open practice workspace",
    openProgress: "Open progress workspace",
    lessonStatus: "Lesson ready",
    attemptReady: "Practice ready",
    offlineStatus: "Offline mode",
    serviceStatus: "Learning service",
    skip: "Skip to main content",
  },
  ar: {
    appName: "مساحة الطالب",
    loading: "جارٍ تحميل مساحة التعلّم…",
    offline: "أنت غير متصل. أعد الاتصال لتحديث أو حفظ نشاط التعلّم.",
    stale: "نعرض آخر درس تم تحميله. إجراءات الخادم متوقفة مؤقتًا أثناء عدم الاتصال.",
    unavailable: "خدمة التعلّم غير متاحة حاليًا.",
    permission: "لا تسمح جلستك بالوصول إلى مساحة الطالب هذه.",
    retry: "إعادة المحاولة",
    navigation: "التنقل في مساحة الطالب",
    home: "الرئيسية",
    study: "المذاكرة",
    practice: "التدريب",
    progress: "التقدّم",
    homeTitle: "مكتبك الدراسي",
    homeSubtitle: "تابع الدرس أو أكمل محاولة تدريب يملكها الخادم أو راجع تقدّمك من مساحة مكتبية واحدة.",
    synthetic: "محتوى اصطناعي تجريبي · ليس منهجًا حقيقيًا",
    currentLesson: "الدرس الحالي",
    continueStudy: "تابع المذاكرة",
    academicContext: "السياق الأكاديمي",
    active: "نشط",
    onboarding: "يلزم إعداد السياق",
    yearLevel: "السنة الدراسية",
    track: "المسار الأكاديمي",
    trackConfigured: "مُحدد بواسطة خدمة التعلّم",
    contextLocked: "السياق الأكاديمي النشط مملوك للخادم ويُقفل بعد الإعداد الأولي.",
    resetReview: "راجع نتائج تغيير المسار",
    resetTitle: "تغيير المسار يتطلب إعادة ضبط كاملة",
    resetBody: "يقوم الخادم بأرشفة السياق السابق والمحاولات والإتقان بدل حذف السجل. وقد تُنهى الأعمال الجارية كجزء من الانتقال.",
    resetGap: "واجهة الويب لا تخترع قائمة مسارات. نحتاج عقدًا من الخادم لقائمة المجلس/المنهج/المسار قبل تفعيل أداة احترافية لتغيير المسار.",
    studyTitle: "مساحة المذاكرة",
    studySubtitle: "اقرأ الدرس المنشور بعرض مريح لسطح المكتب واتجاه محتوى مناسب للغة.",
    contentVersion: "إصدار المحتوى",
    lessonEmpty: "لا يوجد درس منشور متاح في هذا السياق.",
    practiceTitle: "مساحة التدريب",
    practiceSubtitle: "اختيار الأسئلة وترتيبها يأتي فقط من المحاولة المحفوظة في الخادم. لا تُنشئ الواجهة بذرة تقييم أو ترتيبًا معتمدًا.",
    authoritative: "محاولة معتمدة من الخادم",
    authoritativeNote: "البدء ينشئ محاولة على الخادم، وإعادة الاتصال تستأنف نفس الترتيب المحفوظ.",
    start: "ابدأ تدريبًا جديدًا",
    starting: "جارٍ بدء التدريب…",
    resume: "استئناف التدريب",
    submitting: "جارٍ الحفظ والإرسال…",
    submit: "احفظ الإجابات وأرسل",
    answerRequired: "أجب عن جميع الأسئلة قبل الإرسال.",
    conflict: "تغيّرت المحاولة على الخادم. تم تحميل النسخة المعتمدة المحفوظة؛ راجع إجاباتك ثم تابع.",
    noAttempt: "لا توجد محاولة تدريب جارية.",
    question: "السؤال",
    textAnswer: "الإجابة",
    saved: "محفوظ",
    result: "نتيجة التدريب",
    attemptStatus: "حالة المحاولة",
    progressTitle: "مساحة التقدّم",
    progressSubtitle: "يُقرأ التقدّم من السياق الأكاديمي النشط؛ ولا تحسب الواجهة الإتقان بشكل مستقل.",
    mastery: "الإتقان",
    emptyProgress: "أكمل تدريبًا لإنشاء أول سجل للتقدّم.",
    snapshots: "سجلات التقدّم",
    openStudy: "افتح مساحة المذاكرة",
    openPractice: "افتح مساحة التدريب",
    openProgress: "افتح مساحة التقدّم",
    lessonStatus: "الدرس جاهز",
    attemptReady: "التدريب جاهز",
    offlineStatus: "وضع عدم الاتصال",
    serviceStatus: "خدمة التعلّم",
    skip: "انتقل إلى المحتوى الرئيسي",
  },
  fr: {
    appName: "Espace élève",
    loading: "Chargement de votre espace d’apprentissage…",
    offline: "Vous êtes hors ligne. Reconnectez-vous pour actualiser ou enregistrer l’activité.",
    stale: "La dernière leçon chargée reste visible. Les actions serveur sont suspendues hors ligne.",
    unavailable: "Le service d’apprentissage est indisponible pour le moment.",
    permission: "Votre session ne peut pas accéder à cet espace élève.",
    retry: "Réessayer",
    navigation: "Navigation de l’espace élève",
    home: "Accueil",
    study: "Étude",
    practice: "Exercice",
    progress: "Progression",
    homeTitle: "Votre bureau d’apprentissage",
    homeSubtitle: "Reprenez la leçon, continuez une tentative gérée par le serveur ou consultez votre progression depuis un espace de bureau unique.",
    synthetic: "Contenu synthétique de test · aucun programme réel",
    currentLesson: "Leçon actuelle",
    continueStudy: "Continuer l’étude",
    academicContext: "Contexte académique",
    active: "Actif",
    onboarding: "Configuration requise",
    yearLevel: "Niveau scolaire",
    track: "Parcours académique",
    trackConfigured: "Configuré par le service d’apprentissage",
    contextLocked: "Le contexte académique actif appartient au Backend et reste verrouillé après l’intégration.",
    resetReview: "Voir les conséquences d’un changement de parcours",
    resetTitle: "Changer de parcours déclenche une réinitialisation complète",
    resetBody: "Le Backend archive l’ancien contexte, les tentatives et la maîtrise au lieu de supprimer l’historique. Un travail en cours peut être abandonné pendant la transition.",
    resetGap: "Le client Web n’invente pas de catalogue de parcours. Un contrat Backend de sélection conseil/programme/parcours est requis avant d’activer un contrôle professionnel de changement.",
    studyTitle: "Espace d’étude",
    studySubtitle: "Lisez la leçon publiée dans une largeur confortable pour ordinateur, avec une direction adaptée à la langue du contenu.",
    contentVersion: "Version du contenu",
    lessonEmpty: "Aucune leçon publiée n’est disponible dans ce contexte.",
    practiceTitle: "Espace d’exercice",
    practiceSubtitle: "La sélection et l’ordre des questions proviennent uniquement de la tentative persistée par le Backend. Le client ne génère jamais de graine ni d’ordre autoritaire.",
    authoritative: "Tentative autoritaire du serveur",
    authoritativeNote: "Le démarrage crée une tentative Backend ; la reconnexion reprend exactement cet ordre persisté.",
    start: "Commencer un nouvel exercice",
    starting: "Démarrage de l’exercice…",
    resume: "Reprendre l’exercice",
    submitting: "Enregistrement et envoi…",
    submit: "Enregistrer les réponses et envoyer",
    answerRequired: "Répondez à toutes les questions avant l’envoi.",
    conflict: "La tentative a changé sur le serveur. La version autoritaire persistée a été rechargée ; vérifiez vos réponses puis continuez.",
    noAttempt: "Aucun exercice n’est en cours.",
    question: "Question",
    textAnswer: "Réponse",
    saved: "Enregistré",
    result: "Résultat de l’exercice",
    attemptStatus: "Statut de la tentative",
    progressTitle: "Espace de progression",
    progressSubtitle: "La progression vient du contexte académique actif ; ce client ne recalcule pas la maîtrise de son côté.",
    mastery: "Maîtrise",
    emptyProgress: "Terminez un exercice pour créer votre premier instantané de progression.",
    snapshots: "Instantanés de progression",
    openStudy: "Ouvrir l’espace d’étude",
    openPractice: "Ouvrir l’espace d’exercice",
    openProgress: "Ouvrir la progression",
    lessonStatus: "Leçon prête",
    attemptReady: "Exercice prêt",
    offlineStatus: "Mode hors ligne",
    serviceStatus: "Service d’apprentissage",
    skip: "Aller au contenu principal",
  },
} as const;

export function directionForLocale(locale: Locale): "rtl" | "ltr" {
  return locale === "ar" ? "rtl" : "ltr";
}

export function localize(value: LocalizedText, locale: Locale): string {
  return value[locale] ?? value.en ?? value.ar ?? value.fr ?? "";
}
