<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Install MODRIK</title>
<style>body{font-family:system-ui;background:#f8fafc;color:#0f172a;margin:0}.wrap{max-width:760px;margin:3rem auto;padding:1rem}.card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:1.5rem;box-shadow:0 8px 25px #0f172a12}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}label{display:block;font-weight:600;font-size:.9rem}input{width:100%;box-sizing:border-box;padding:.7rem;border:1px solid #cbd5e1;border-radius:8px;margin-top:.3rem}button{background:#25546f;color:#fff;border:0;border-radius:9px;padding:.8rem 1.2rem;font-weight:700}.secondary{background:#e2e8f0;color:#0f172a}.actions{display:flex;justify-content:space-between;gap:1rem;margin-top:1.5rem}.ok{color:#15803d}.bad,.errors{color:#b91c1c}.steps{color:#475569;font-size:.9rem;margin-bottom:1rem}.panel[hidden]{display:none}.review{line-height:1.7}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head>
<body><main class="wrap" data-testid="modrik-installer-wizard"><h1>MODRIK Setup Wizard</h1><p class="steps" id="step-label">Welcome · Step 1 of 8</p>
@if($errors->any())<div class="card errors">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form method="post" action="{{ route('installer.submit') }}" class="card" id="installer-form">@csrf
<section class="panel" data-step="0"><h2>Welcome</h2><p>This guided installation creates the first Admin, writes a new protected Backend environment, runs migrations, and permanently locks the installer.</p><p>Existing <code>.env</code> files are never overwritten.</p></section>
<section class="panel" data-step="1" hidden><h2>Requirements</h2>@foreach($requirements as $name=>$ok)<p class="{{ $ok?'ok':'bad' }}">{{ $ok?'✓':'✕' }} {{ str_replace('_',' ',$name) }}</p>@endforeach @if(in_array(false,$requirements,true))<p class="bad">Resolve every failed requirement before continuing.</p>@endif</section>
<section class="panel" data-step="2" hidden><h2>Database</h2><div class="grid"><label>Database host<input name="db_host" value="{{ old('db_host','127.0.0.1') }}" required></label><label>Database port<input name="db_port" type="number" min="1" max="65535" value="{{ old('db_port',3306) }}" required></label><label>Database name<input name="db_database" value="{{ old('db_database') }}" required></label><label>Database user<input name="db_username" value="{{ old('db_username') }}" required></label><label>Database password<input name="db_password" type="password" autocomplete="new-password" required></label></div><p>Database authentication is attempted only during final installation; a failure is reported without retaining the password.</p></section>
<section class="panel" data-step="3" hidden><h2>URLs and runtime identity</h2><div class="grid"><label>Backend URL<input name="app_url" type="url" value="{{ old('app_url') }}" required></label><label>Web URL<input name="web_url" type="url" value="{{ old('web_url') }}" required></label><label>Release SHA<input name="release_sha" pattern="[0-9a-fA-F]{40}" value="{{ old('release_sha') }}" required></label></div><p>The wizard records the supplied immutable release identity. It does not claim or configure a Node/cPanel restart.</p></section>
<section class="panel" data-step="4" hidden><h2>First Admin</h2><div class="grid"><label>Admin email<input name="admin_email" type="email" value="{{ old('admin_email') }}" required></label><label>Admin password<input name="admin_password" type="password" minlength="12" autocomplete="new-password" required></label></div><p>Use at least 12 characters including uppercase, lowercase, and a number.</p></section>
<section class="panel review" data-step="5" hidden><h2>Review</h2><p id="review-safe"></p><p>Passwords and generated APP_KEY values are deliberately excluded from this review and from error output.</p></section>
<section class="panel" data-step="6" hidden><h2>Install</h2><p>Installation will test the database, generate APP_KEY, atomically write <code>.env</code>, run migrations, create the first Admin, and write the installation lock.</p><button type="submit" data-testid="installer-submit">Install MODRIK</button></section>
<div class="actions"><button type="button" class="secondary" id="back" hidden>Back</button><button type="button" id="next">Continue</button></div></form></main>
<script>(()=>{const panels=[...document.querySelectorAll('.panel')],labels=['Welcome','Requirements','Database','URLs / Runtime','Admin','Review','Install'];let step=0;const next=document.querySelector('#next'),back=document.querySelector('#back'),label=document.querySelector('#step-label'),form=document.querySelector('#installer-form');function render(){panels.forEach((p,i)=>p.hidden=i!==step);label.textContent=`${labels[step]} · Step ${step+1} of 8`;back.hidden=step===0;next.hidden=step===panels.length-1;if(step===5){const read=n=>form.elements[n].value;document.querySelector('#review-safe').textContent=`Database: ${read('db_database')} on ${read('db_host')}:${read('db_port')} · Backend: ${read('app_url')} · Web: ${read('web_url')} · Admin: ${read('admin_email')} · Release: ${read('release_sha')}`;}}next.addEventListener('click',()=>{for(const input of panels[step].querySelectorAll('input'))if(!input.reportValidity())return;if(step<panels.length-1){step++;render();}});back.addEventListener('click',()=>{if(step>0){step--;render();}});render();})();</script></body></html>
